modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gg"
version="1.0.0"
displayName="gg"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="admin, MCreator"

[[dependencies.gg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




